apiVersion: apps/v1
kind: Deployment
metadata:
  name: finconvert-backend
  labels:
    app: finconvert-backend
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: finconvert-backend
  template:
    metadata:
      labels:
        app: finconvert-backend
    spec:
      automountServiceAccountToken: false 
      containers:
      - name: backend
        image: aniketsharma05/finconvert-backend:v1.0.0 
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "50Mi" 
          limits:
            memory: "256Mi"
            cpu: "250m"
            ephemeral-storage: "100Mi"