apiVersion: apps/v1
kind: Deployment
metadata:
  name: finconvert-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: finconvert-backend:latest
        imagePullPolicy: Never # Crucial: Tells K8s to use your local Jenkins-built image
        ports:
        - containerPort: 5000
        env:
        - name: EXCHANGE_API_URL
          value: "https://open.er-api.com/v6/latest" 
        - name: CORS_ORIGINS
          value: "http://localhost"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer # Exposes the container to your local Windows machine
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000