apiVersion: v1
kind: Service
metadata:
  name: finconvert-backend-service
spec:
  type: NodePort
  selector:
    app: finconvert-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30050