apiVersion: apps/v1
kind: Deployment
metadata:
  name: finconvert-frontend
  labels:
    app: finconvert-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finconvert-frontend
  template:
    metadata:
      labels:
        app: finconvert-frontend
    spec:
      automountServiceAccountToken: false
      containers:
      - name: frontend
        image: aniketsharma05/finconvert-frontend:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
            ephemeral-storage: "50Mi"
          limits:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "100Mi"